### PR TITLE
Fix for improper branched project name

### PR DESCRIPTION
**Pull request by HussainS12**
This PR fixes the issue with improper branched project name generation.

### CODE REVIEW

**Comment by satyamchaurasiapersistent** [comment]
Hi @HussainS12  can you please mention this issue in detail and how to reproduce issue. I need to verify this issue and fix provided by you then we can include this code in this SDK.

**Review by satyamchaurasiapersistent — COMMENTED** [review]
Hi @HussainS12 can you please mention this issue in detail and how to reproduce issue. I need to verify this issue and fix provided by you then we can include this code in this SDK.

**Comment by HussainS12** [comment]
Hi @satyamchaurasiapersistent The issue is described here https://github.com/checkmarx-ltd/cx-flow/issues/1161 . Whenever the user sends the branch param as blank or empty cx-flow creates a weird branched project name in cx-sast, it is happening because the code tries to replace value of empty string with some other strings and it is creating long and weird branched project name.

**Comment by satyamchaurasiapersistent** [comment]
HI @HussainS12 Thanks for your contribution. Your contribution helped us to resolve issue but we need make more changes in our code in order to resolve this issue . So we are not merging your code but the issue is resolved in latest release.

Once again Thanks for your contribution. Keep contributing :-) Best of luck 

Regards
Satyam Chaurasia

**Pull request closed without merging**
